name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        toxenv: [ 'qa', 'py313' ]
        include:
          - toxenv: py313
            python: 3.13
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Cache OS python libs
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip/
          key: ${{ runner.os }}-py${{ matrix.python }}

      - name: Cache tox python
        uses: actions/cache@v4
        with:
          path: ./.tox
          key: >
            ${{ runner.os }}-
            tox${{ matrix.toxenv }}-
            ${{ hashFiles(
               'uv.lock',
               '.github/cache.key')
            }}

      - name: Install tox
        run: python -m pip install tox

      - name: Run tox with parameter
        run: tox -e ${{ matrix.toxenv }}

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.toxenv }}
          path: coverage_html_report/
          if-no-files-found: ignore